# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

fs = import('fs')
fs.copyfile('__init__.py')
fs.copyfile('device.py')
fs.copyfile('runtime.py')

# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

fs = import('fs')
fs.copyfile('__init__.py')
fs.copyfile('device.py')
fs.copyfile('runtime.py')

