# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

fs = import('fs')
fs.copyfile('_bindings.py')
fs.copyfile('_helpers.py')
fs.copyfile('_structs.py')
fs.copyfile('__init__.py')
fs.copyfile('device.py')
fs.copyfile('runtime.py')

